### ISSUE TITLE
def get_cnn(self)-> telegram.bot.Bot: AttributeError: module 'telegram' has no attrivute 'bot'

### ISSUE THREAD

**Issue by philip-shen** [ChickenBenny/Airflow-scraping-ETL-tutorial#1]
python_package, modify below texts in requirements.txt 
------------------------------------------------------
apache-airflow-providers-telegram==3.0.0
python-telegram-bot==13.15

**Comment by ChickenBenny** [comment]
Fix, thanks a lot!
